services:
    codefog_tags.listener.insert_tags:
        class: Codefog\TagsBundle\EventListener\InsertTagsListener
        arguments:
            - "@codefog_tags.manager_registry"

    codefog_tags.listener.tag_manager:
        class: Codefog\TagsBundle\EventListener\TagManagerListener
        arguments:
            - "@codefog_tags.manager_registry"

    codefog_tags.listener.data_container.tag:
        class: Codefog\TagsBundle\EventListener\DataContainer\TagListener
        arguments:
            - "@database_connection"
            - "@contao.framework"
            - "@codefog_tags.manager_registry"
            - "@request_stack"
            - "@session"
